Support classpath protocol
openhtmltopdf/openhtmltopdf pull request #3
Opened 2024-01-24 14:06 UTC by daniel-shuy

Support URLs with the `classpath` protocol, e.g. `classpath:/path/to/file`

Credits to @aleks-shbln for the original implementation (https://github.com/danfickle/openhtmltopdf/issues/146#issuecomment-612456562).

The original implementation depends on Spring Framework, which `openhtmltopdf` does not. I've re-implemented it to be framework-agnostic.

I've also made it more consistent with the other `FSStreamFactory` implementations (logging instead of throwing Exception on error).

The `ClassPathStreamFactory` is registered by default, so that the `classpath` protocol is supported out-of-the-box. There's no need to manually register it.

p.s. this was such a pain because the indentations of `NaiveUserAgent.java` is such a mess (mix of tabs and spaces)

2024-01-25 19:19 UTC, siegelzc commented
do you have any idea why the package is called "swing"?

2024-01-25 19:28 UTC, siegelzc requested changes

2024-01-25 19:28 UTC, zacharysiegel commented on openhtmltopdf-core/src/main/java/com/openhtmltopdf/swing/NaiveUserAgent.java
> +    private final ClassLoader classLoader = getClassLoader();
Since retrieving the appropriate `ClassLoader` is a tricky process, I think it would be nice to add a secondary constructor here that would allow the user to specify their own `ClassLoader` (or perhaps a callback function which produces a `ClassLoader`.

2024-01-25 19:43 UTC, siegelzc commented
also, feel free to run your IDE's formatter on that file

2024-01-26 10:16 UTC, daniel-shuy commented
> do you have any idea why the package is called "swing"?

Beats me 🤷‍♂️

2024-01-26 10:16 UTC, daniel-shuy commented on openhtmltopdf-core/src/main/java/com/openhtmltopdf/swing/NaiveUserAgent.java
> +    private final ClassLoader classLoader = getClassLoader();
Done

2024-01-26 19:26 UTC, siegelzc approved these changes

2024-01-26 19:32 UTC, merged