Signature fields for digital signage
openhtmltopdf/openhtmltopdf pull request #37
Opened 2024-04-26 15:00 UTC by burka

Added signature fields for digital signing & fixed FormFields not to span multiple pages due to wrong position calculation.
See src/main/resources/visualtest/html/form-signature-field.html for an example.

See https://github.com/danfickle/openhtmltopdf/issues/681 for the old issue for the signature and https://github.com/danfickle/openhtmltopdf/issues/914 for the old issue for the forms with wrong positioning :-) 

Thanks for keeping this project alive!

2024-04-29 07:55 UTC, burka commented
Removed the space-only changes.

2024-05-01 19:54 UTC, zacharysiegel commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxForm.java
>  import com.openhtmltopdf.util.LogMessageId;
```suggestion
import com.openhtmltopdf.css.constants.CSSName;
import com.openhtmltopdf.css.constants.IdentValue;
import com.openhtmltopdf.css.parser.FSCMYKColor;
import com.openhtmltopdf.css.parser.FSColor;
import com.openhtmltopdf.css.parser.FSRGBColor;
import com.openhtmltopdf.render.Box;
import com.openhtmltopdf.render.PageBox;
import com.openhtmltopdf.render.RenderingContext;
import com.openhtmltopdf.util.ArrayUtil;
```

After pulling the branch, I had to add these imports to get the file to compile.

2024-05-01 19:54 UTC, zacharysiegel commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxForm.java
> +import java.util.stream.Collectors;
![Screenshot 2024-05-01 at 10 12 35 AM](https://github.com/openhtmltopdf/openhtmltopdf/assets/15002786/a36fb6c6-e8ff-46e6-bd7b-638f9f4c24be)


I'm also seeing that these are all unused.

2024-05-01 19:54 UTC, zacharysiegel commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxAccessibilityHelper.java
> +                            _ctx, box, _pageHeight, _transform, _ctx.getPage(), _od);
Is this the relevant line that fixes the cross-page rendering bug?

2024-05-03 11:57 UTC, burka commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxForm.java
> +import java.util.stream.Collectors;
Yeah, sorry, I messed the imports up during my rebase, I hope it's fixed now :-)

2024-05-03 12:04 UTC, burka commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxAccessibilityHelper.java
> +                            _ctx, box, _pageHeight, _transform, _ctx.getPage(), _od);
One of them :-) There are some more changes that are needed, as the root context is used instead of the pageBox at multiple places :-)

2024-05-03 12:07 UTC, burka commented
I fixed the broken imports, hope everything works now :-)

2024-05-04 19:33 UTC, siegelzc requested changes
just typo in test html file

2024-05-04 19:33 UTC, siegelzc commented on openhtmltopdf-examples/src/main/resources/visualtest/html/form-signature-field.html
> +        body {margin:0;padding:0;font-size:10px; font-famliy: TestFont, serif, sans-serif; }
```suggestion
        body {margin:0;padding:0;font-size:10px; font-family: TestFont, serif, sans-serif; }
```

2024-05-06 09:01 UTC, burka commented on openhtmltopdf-examples/src/main/resources/visualtest/html/form-signature-field.html
> +        body {margin:0;padding:0;font-size:10px; font-famliy: TestFont, serif, sans-serif; }
Great @siegelzc ! Thank you :-)

2024-05-06 12:34 UTC, burka commented on openhtmltopdf-pdfbox/src/main/java/com/openhtmltopdf/pdfboxout/PdfBoxForm.java
>  import com.openhtmltopdf.util.LogMessageId;
Should be fixed with those force-pushes **↓**

2024-05-06 18:27 UTC, siegelzc approved these changes

2024-05-06 18:35 UTC, siegelzc requested changes
```
Tests run: 161, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 3.407 sec <<< FAILURE!
testSignatureField(com.openhtmltopdf.visualregressiontests.VisualRegressionTest)  Time elapsed: 0.077 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.openhtmltopdf.visualregressiontests.VisualRegressionTest.testSignatureField(VisualRegressionTest.java:1518)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at com.openhtmltopdf.testlistener.PrintingRunner.run(PrintingRunner.java:17)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testSignatureField(com.openhtmltopdf.visualregressiontests.VisualRegressionTest)

Tests run: 369, Failures: 1, Errors: 0, Skipped: 21
```

2024-05-07 07:24 UTC, burka commented
Thanks!  Can someone start the workflow? :-)  @siegelzc

2024-05-07 17:57 UTC, siegelzc approved these changes

2024-05-07 17:57 UTC, siegelzc commented
merge when ready. the release action can be ignored

2024-05-13 12:50 UTC, burka commented
Thanks! Who can merge the PR? Is there anything I can do?

2024-05-13 13:27 UTC, siegelzc commented
> Thanks! Who can merge the PR? Is there anything I can do?

Oh, I'll go ahead and merge it. I thought if I approved, then you would be able to merge. I'll look in to the repository permissions on that.

2024-05-13 13:28 UTC, merged

2024-05-13 13:35 UTC, burka commented
Great, thanks!