Improve ClassCondition performance
openhtmltopdf/openhtmltopdf pull request #8
Opened 2024-01-30 08:45 UTC by jochenberger

fixes #1

2024-01-31 05:13 UTC, siegelzc commented
When I get the chance, I want to run the profiler with @hikariqz's [test file](https://github.com/openhtmltopdf/openhtmltopdf/files/14076114/test.txt) to compare the two branches.

2024-01-31 15:02 UTC, Hikariqz commented
It looks awesome, will test in my locally as well. Thank you all very much @jochenberger @siegelzc !

2024-02-07 19:06 UTC, siegelzc requested changes
I tested it with the IntelliJ profiler, and perhaps I'm just using it wrong, but I don't see this memory usage spike. I like the change though, just see my other comment.

2024-02-07 19:06 UTC, zacharysiegel commented on openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/newmatch/Condition.java
> +            return endOfMatch < c.length() && c.charAt(endOfMatch) == ' ';
This code was a bit difficult to decipher, I think the below is a bit nicer.

From [this spec](https://www.w3.org/TR/CSS21/grammar.html#scanner), it looks like we should be checking for the other whitespace characters as well, beyond just `' '`, so I use `Character.isWhitespace` rather than `== ' '`.

```suggestion
            int beforeMatch = idx - 1;
            int afterMatch = idx + _className.length();
            boolean delimitedBefore = beforeMatch < 0 || Character.isWhitespace(c.charAt(beforeMatch));
            boolean delimitedAfter = afterMatch == c.length() || Character.isWhitespace(c.charAt(afterMatch));
            return delimitedBefore && delimitedAfter;
```

2024-02-07 20:27 UTC, jochenberger commented on openhtmltopdf-core/src/main/java/com/openhtmltopdf/css/newmatch/Condition.java
> +            return endOfMatch < c.length() && c.charAt(endOfMatch) == ' ';
Go ahead and change it according to your liking then, I don't mind.

2024-02-07 21:21 UTC, siegelzc approved these changes

2024-02-07 21:56 UTC, merged

2024-02-09 08:06 UTC, jochenberger commented
I guess the results will depend on your hardware, JVM version, and JVM settings.
Any insights @Hikariqz ?

2024-02-19 16:36 UTC, Hikariqz commented
I think so. When I using JDK17 with vm option -Xmx2g -Xms2g, there is clearly memory usage spike. Please find the snippshot 1 below.
![image](https://github.com/openhtmltopdf/openhtmltopdf/assets/157510283/cc0e02b6-538a-4fc1-83d5-36521efe6136)

However, the memory usage is relatively low, almost below 400MB when test it without vm options. Please find the snippshot2 below. (the default max heap size 4GB in my pc).
![image](https://github.com/openhtmltopdf/openhtmltopdf/assets/157510283/03dae192-7d03-48a5-8d82-f21c3b1469df)

I am guessing the memory spike is cause by jvm option differences, any idea about it?
Will analysis more and get back to you.

2024-02-20 04:49 UTC, siegelzc commented
It is interesting to me that there are so many more young generation garbage collection events in the 4gb heap vs the 2gb